module.exports = {
  required: "Please fill all required fields.",
  userNotFound: "User not found.",
  businessNotFound: "Business not found",
  userNotVerified: "User not verified",
  accountNotFound: "Account does not exists",
  emailAlreadyExists: "Email already exists",
  emailAlreadyExistsButNotVerify: "Email already exists but does not verified in our record",
  emailNotFound: "Email does not match with our records",
  accountAlreadyVerified: "Email already verified in our record",
  accountAlreadySetupProfile: "Email already setup their profile in our record",
  otpNotVerified: "OTP not verified",
  otpExpired: "OTP expired",
  subscriptionNotFound: "Subscription not found",
  applicationNotFound: "Application not found",
  templateNotFound: "Template not found",
  shiftNotFound: "Shift not found",
  jobNotFound: "Job not found",
  serverError: "Internal Server Error",
  badRequest: "Bad Request",
  invalidCredentials: "Invalid Credentials",
  passwordTooWeak:
    "Password must be 8 characters long and include at least one uppercase letter, one digit, and one special character",
  availabilityNotFound: "Availability not present",
  jobInstructionsNotFound: "Job instructions not found",
  DetailNotFound: "Detail Not Found",
  userSubscriptionNotFound: "User Subscription not found",
};
